accessibility: Hidden
comment: Lists all applications (databases) in baserow
↓Call_Sequence [steps.SequenceStep-1666716889015]: 
  sourceSequence: lib_BaseRow.TokenGetOrRefresh
↓Call_Transaction [steps.TransactionStep-1665210509901]: 
  sourceTransaction: lib_BaseRow.Baserow_API_spec._api_applications__GET
  ↓__header_Authorization [variables.StepVariable-1665211142280]: 
    sourceDefinition: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
        - com.twinsoft.convertigo.beans.common.XMLVector: 
          - java.lang.String: 
            - ↑value: 1666716889015
          - java.lang.String: 
            - ↑value: ./document/Bearer/text()
↓Copy [steps.XMLCopyStep-1665295585596]: 
  sourceDefinition: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
      - com.twinsoft.convertigo.beans.common.XMLVector: 
        - java.lang.String: 
          - ↑value: 1665210509901
        - java.lang.String: 
          - ↑value: ./document/array