comment: Lists all applications (databases) in baserow
↓GetTokenFromSession [steps.SessionGetStep-1665210481031]: 
  key: token
  output: false
↓Concat [steps.XMLConcatStep-1665211330857]: 
  nodeName: Bearer
  output: false
  sourcesDefinition: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
      - com.twinsoft.convertigo.beans.common.XMLVector: 
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
          - com.twinsoft.convertigo.beans.common.XMLVector: 
            - java.lang.String: 
              - ↑value: description
            - xmlizable: 
              - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
              - com.twinsoft.convertigo.beans.common.XMLVector: 
            - java.lang.String: 
              - ↑value: JWT
        - xmlizable: 
          - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
          - com.twinsoft.convertigo.beans.common.XMLVector: 
            - java.lang.String: 
              - ↑value: description
            - xmlizable: 
              - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
              - com.twinsoft.convertigo.beans.common.XMLVector: 
                - java.lang.String: 
                  - ↑value: 1665210481031
                - java.lang.String: 
                  - ↑value: ./expression/text()
            - java.lang.String: 
              - ↑value: ''
↓Call_Transaction [steps.TransactionStep-1665210509901]: 
  sourceTransaction: lib_BaseRow.Baserow_API_spec._api_applications__GET
  ↓__header_Authorization [variables.StepVariable-1665211142280]: 
    sourceDefinition: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
        - com.twinsoft.convertigo.beans.common.XMLVector: 
          - java.lang.String: 
            - ↑value: 1665211330857
          - java.lang.String: 
            - ↑value: ./text()
↓Copy [steps.XMLCopyStep-1665295585596]: 
  sourceDefinition: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
      - com.twinsoft.convertigo.beans.common.XMLVector: 
        - java.lang.String: 
          - ↑value: 1665210509901
        - java.lang.String: 
          - ↑value: ./document/array