accessibility: Hidden
authenticatedContextRequired: true
comment: Lists all applications (databases) in baserow
↓Call_Sequence1 [steps.SequenceStep-1729092945742]: 
  sourceSequence: C8Oforms.BaserowAccountGet
↓IfExist [steps.IfExistStep-1729094183282]: 
  sourceDefinition: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
      - com.twinsoft.convertigo.beans.common.XMLVector: 
        - java.lang.String: 
          - ↑value: 1729092945742
        - java.lang.String: 
          - ↑value: ./document/error
  ↓Copy [steps.XMLCopyStep-1729094212640]: 
    sourceDefinition: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
        - com.twinsoft.convertigo.beans.common.XMLVector: 
          - java.lang.String: 
            - ↑value: 1729092945742
          - java.lang.String: 
            - ↑value: ./document/error
  ↓Return [steps.ReturnStep-1729094274248]: 
↓Call_Sequence [steps.SequenceStep-1666716889015]: 
  sourceSequence: lib_BaseRow.TokenGetOrRefresh
  ↓password [variables.StepVariable-1729092959271]: 
    comment: The baserow admin password
    sourceDefinition: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
        - com.twinsoft.convertigo.beans.common.XMLVector: 
          - java.lang.String: 
            - ↑value: 1729092945742
          - java.lang.String: 
            - ↑value: ./document/password/text()
    value: 
      - ↑ciphered: true
      - ↑traceable: false
      - →→: xd8e180806a1c1d83a6255212121ab827
    visibility: '-1'
  ↓email [variables.StepVariable-1729092959273]: 
    comment: The Base row admin email
    sourceDefinition: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
        - com.twinsoft.convertigo.beans.common.XMLVector: 
          - java.lang.String: 
            - ↑value: 1729092945742
          - java.lang.String: 
            - ↑value: ./document/email/text()
↓Call_Transaction [steps.TransactionStep-1665210509901]: 
  sourceTransaction: lib_BaseRow.Baserow_API_spec._api_applications__GET
  ↓__header_Authorization [variables.StepVariable-1665211142280]: 
    sourceDefinition: 
      - xmlizable: 
        - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
        - com.twinsoft.convertigo.beans.common.XMLVector: 
          - java.lang.String: 
            - ↑value: 1666716889015
          - java.lang.String: 
            - ↑value: ./document/Bearer/text()
↓Copy [steps.XMLCopyStep-1665295585596]: 
  sourceDefinition: 
    - xmlizable: 
      - ↑classname: com.twinsoft.convertigo.beans.common.XMLVector
      - com.twinsoft.convertigo.beans.common.XMLVector: 
        - java.lang.String: 
          - ↑value: 1665210509901
        - java.lang.String: 
          - ↑value: ./document/array